"""Build Moss's sprite library: generate missing poses once, then cut them out.

    python scripts/build_moss_sprites.py            # cut existing poses only
    python scripts/build_moss_sprites.py --generate # also generate missing poses (FAL)

Poses are generated by an image-edit model from the approved canonical reference
(assets/moss/moss_canonical.png), on a flat navy ground so they cut cleanly.
Each costs about $0.039 and is generated once; videos then animate the sprites
in code for free (see moss_sprite.py).
"""
import argparse
import sys
from io import BytesIO
from pathlib import Path

import numpy as np
import requests
from dotenv import load_dotenv
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
REFERENCES = ROOT / "assets" / "moss"
SPRITES = REFERENCES / "sprites"
EDIT_MODEL = "fal-ai/nano-banana/edit"

IDENTITY = (
    "Redraw exactly the character in the attached reference image: same "
    "chunky 16-bit pixel art style, same mint-green bean-shaped body with "
    "creases and a cream belly, same black bead eyes, same brass goggles with "
    "amber lenses, same proportions and the same size in the frame. Full body, "
    "centred, standing on nothing, on a plain solid flat navy-blue background with "
    "no stars, no shadow, no other objects. One character only. No text."
)

# Poses already approved in the style lock are copied, not regenerated.
APPROVED = ("moss_canonical", "moss_front", "moss_side", "moss_thinking")
GENERATED = {
    "moss_amazed": "Pose: facing the viewer, goggles pulled DOWN over both eyes, mouth a small open round 'o', amazed.",
    "moss_point": "Pose: three-quarter view facing right, one front claw stretched out pointing to the right, curious.",
    "moss_wave": "Pose: facing the viewer, one front claw raised high and waving, friendly smile.",
    "moss_delighted": "Pose: facing the viewer, eyes closed in happy upturned arcs, smile, both front claws raised, joyful. No glow or outline.",
    "moss_blink": "Pose: identical to the reference but both eyes closed as short flat horizontal lines.",
    "moss_walk_a": "Pose: side view facing right, mid-step: front feet stepping forward, back feet pushing off.",
    "moss_walk_b": "Pose: side view facing right, mid-step: the opposite feet forward from a normal walk cycle.",
}


def generate_pose(name: str, instruction: str) -> None:
    import fal_client

    reference = Image.open(REFERENCES / "moss_canonical.png").convert("RGB")
    result = fal_client.run(
        EDIT_MODEL,
        arguments={
            "prompt": f"{IDENTITY}\n\n{instruction}",
            "image_urls": [fal_client.upload_image(reference, format="png")],
            "aspect_ratio": "9:16",
            "num_images": 1,
            "output_format": "png",
        },
        timeout=180,
    )
    response = requests.get(result["images"][0]["url"], timeout=60)
    response.raise_for_status()
    Image.open(BytesIO(response.content)).convert("RGB").save(REFERENCES / f"{name}.png")
    print("generated", name)


def cut_sprite(path: Path, threshold: float = 30.0) -> Image.Image:
    """Return the character as a trimmed RGBA sprite.

    Background is the navy reachable from the frame edge, so dark eyes and
    mouth inside the body stay opaque; only the island under the centre is
    kept, which drops stray star pixels.
    """
    image = Image.open(path).convert("RGB")
    pixels = np.asarray(image).astype(np.int32)
    corners = np.array([pixels[8, 8], pixels[8, -8], pixels[-8, 8], pixels[-8, -8]])
    background = np.median(corners, axis=0)
    distance = np.sqrt(((pixels - background) ** 2).sum(axis=2))
    height, width = distance.shape

    # .copy(): images made by fromarray are read-only, and floodfill would
    # silently do nothing.
    outside = Image.fromarray(((distance <= threshold) * 255).astype(np.uint8), "L").copy()
    ImageDraw.floodfill(outside, (2, 2), 128)
    inside = Image.fromarray(((np.asarray(outside) != 128) * 255).astype(np.uint8), "L").copy()
    centre = (width // 2, height // 2)
    if inside.getpixel(centre) != 255:
        ys, xs = np.nonzero(np.asarray(inside) == 255)
        nearest = np.argmin((xs - centre[0]) ** 2 + (ys - centre[1]) ** 2)
        centre = (int(xs[nearest]), int(ys[nearest]))
    ImageDraw.floodfill(inside, centre, 128)
    mask = np.asarray(inside) == 128
    ys, xs = np.nonzero(mask)
    sprite = image.convert("RGBA")
    sprite.putalpha(Image.fromarray((mask * 255).astype(np.uint8)))
    return sprite.crop((xs.min(), ys.min(), xs.max() + 1, ys.max() + 1))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--generate", action="store_true", help="generate missing poses via FAL")
    args = parser.parse_args()
    load_dotenv(ROOT / ".env")

    if args.generate:
        for name, instruction in GENERATED.items():
            if not (REFERENCES / f"{name}.png").exists():
                generate_pose(name, instruction)

    SPRITES.mkdir(parents=True, exist_ok=True)
    built = 0
    for name in (*APPROVED, *GENERATED):
        source = REFERENCES / f"{name}.png"
        if not source.exists():
            print("missing", name, file=sys.stderr)
            continue
        sprite = cut_sprite(source)
        sprite.save(SPRITES / f"{name.removeprefix('moss_')}.png", optimize=True)
        print("sprite", name, sprite.size)
        built += 1
    return 0 if built else 1


if __name__ == "__main__":
    raise SystemExit(main())
